### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by skaraman** [brumm/atom-highlight-colors#3]
[Enter steps to reproduce:]

1. not sure, clicking around atom? maybe conflict with another package?

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [highlight-colors](https://github.com/brumm/atom-highlight-colors) package 0.8.0

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

Error: Cannot decorate a destroyed marker
    at DecorationManager.decorateMarker (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:518146)
    at TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:27540)
    at HighlightColors.updateDecorations (/packages/highlight-colors/lib/highlight-colors.js:108:16)
    at /packages/highlight-colors/lib/highlight-colors.js:65:16
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 2.0.1 
color-picker 2.3.0 
file-icons 2.1.33 
fold-lines 0.2.2 
fonts 3.4.0 
full-width-tabs 0.3.0 
glowing-cursor 0.1.2 
hey-pane 1.2.0 
highlight-bad-chars 2.0.0 
highlight-bad-chars-bl 1.4.3 
highlight-colors 0.8.0 
highlight-selected 0.16.0 
indentation-indicator 1.1.0 
intentions 1.1.5 
jslint 1.5.1 
language-babel 2.85.0 
language-svg 0.9.2 
linter 2.3.0 
linter-eslint 8.5.5 
linter-gjslint 1.6.0 
linter-jslint 11.1.0 
linter-jslinter 0.2.0 
linter-json-lint 0.1.3 
linter-stylelint 4.4.9 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-lens 0.3.0 
minimap-linter 2.2.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
multiline-tab 0.2.1 
pigments 0.40.2 
pretty-json 2.1.2 
soft-wrap-indicator 1.1.0 
svg-preview 0.14.0 
syntax-neonize 3.3.0 
tabs-to-spaces 1.0.5 
teletype 0.13.4 
tinacious-design-syntax-purple 0.5.1 
```

**Comment by therealokoro** [comment]
I also have this problem. It pops up that warning at random, but doesn't really affect my work flow. Well only that it is very annoying to see.

Please any fix for this problem will be welcomed. Thanks

**Comment by brumm** [comment]
Hey, thanks for the report. I haven't encountered this yet, but I'll keep an eye out.

**Comment by skaraman** [comment]
I haven't had this issue on quite some time, I'm using the latest Atom and package versions.

**Comment by brumm** [comment]
@skaraman Thanks for the update (and sorry for this late reply), I'll close this out because this hasn't occurred here either in the meantime.
